### PR TITLE
Ensured that every new cookbook has at least one menu plan

### PR DESCRIPTION
**Pull request by boblail**
### Details

 - Menu Plans belong to cookbooks (should these be called "families"?) not to users so that spouses can collaborate on them
 - When a new user signs up, they'll implicitly have a cookbook (to which other users can be added) and that cookbook will have a first menu plan (so they can start adding recipes to it)

### CODE REVIEW

**Comment by boblail** [comment]
@clettenberg, do you want to do PRs like this?

**Comment by boblail** [comment]
If you want — if not, that's totally fine — after this PR is merged, I could work on

 - adding recipes to the current menu plan
 - showing if recipe is in the current menu plan
 - removing a recipe from the current menu plan

and you could work on

 - showing the current menu plan in the navbar
 - letting you create a new menu plan
 - letting you switch between menu plans

* * *

I figure this might be the first thing that stops being 100% Rails-rendered. I mean, if I tap "Add to Menu Plan", I think the view should react right away without a full-page reload (so I don't lose my scroll position).

Do you think we should:
  1. Just write vanilla JavaScript for now
  2. Use Backbone models (and maybe Handlebars templates — which could pave the way to Ember or be swapped out for React later)
  3. Introduce Ember or Angular

(It _feels_ like 3. might be YAGNI; I lean a little toward 2. — probably b/c of Houston — but I'm OK with 1. What do you think?)

**Comment by clettenberg** [comment]
I agree with 2. I think that will give us the most flexibility in the future. 

React/Backbone/Coffeescript is what [Missive uses](https://medium.com/missive-app/our-dirty-little-secret-cross-platform-email-client-with-nothing-but-html-aa12fc33bb02) and they use electron/phonegap to support other platforms. 

I hadn't done a whole lot on the Turbolinks front, should we shelf that for now?

**Comment by clettenberg** [comment]
I think it makes sense to keep it `cookbook` and it might make sense to introduce the concept of `family` (or something else that means a group of users). 

I could see both of those models growing over time and becoming more "specialized" ( cookbooks knowing everything about a group of recipes and families knowing everything about a group of users).

**Pull request merged**
